task_homepage:
    path:     /task
    defaults: { _controller: LeaderITTaskBundle:Default:index }

task_post:
    path:     /task/api/task/{id}
    defaults: { _controller: LeaderITTaskBundle:Task:post, id: 0 }
    requirements:
        _method:  POST

task_delete:
    path:     /task/api/task/{id}
    defaults: { _controller: LeaderITTaskBundle:Task:delete }
    requirements:
        _method:  DELETE

day_get:
    path:     /task/api/day/{day}
    defaults: { _controller: LeaderITTaskBundle:Day:get, day: 0 }
    requirements:
        _method:  GET

day_post:
    path:     /task/api/day
    defaults: { _controller: LeaderITTaskBundle:Day:post}
    requirements:
        _method:  POST