task_redirect:
    path:     /
    defaults: { _controller: LeaderITTaskBundle:Default:redirect }

task_homepage:
    path:     /task/{date}
    defaults: { _controller: LeaderITTaskBundle:Default:index, date: ''}

task_login:
    path:     /login
    defaults: { _controller: LeaderITTaskBundle:Security:index}

task_login_check:
    path:     /task/check
    defaults: { _controller: LeaderITTaskBundle:Security:check}

task_logout:
    path:     /task/logout
    defaults: { _controller: LeaderITTaskBundle:Security:logout}

task_get:
    path:     /task/api/task/{id}
    defaults: { _controller: LeaderITTaskBundle:Task:get }
    requirements:
        _method:  GET

task_post:
    path:     /task/api/task/{id}
    defaults: { _controller: LeaderITTaskBundle:Task:post, id: 0 }
    requirements:
        _method:  POST

task_delete:
    path:     /task/api/task/{id}
    defaults: { _controller: LeaderITTaskBundle:Task:delete }
    requirements:
        _method:  DELETE

day_get:
    path:     /task/api/day/{day}
    defaults: { _controller: LeaderITTaskBundle:Day:get, day: 0 }
    requirements:
        _method:  GET

day_pull:
    path:     /task/api/day/pull
    defaults: { _controller: LeaderITTaskBundle:Day:pull}
    requirements:
        _method:  POST

day_post:
    path:     /task/api/day
    defaults: { _controller: LeaderITTaskBundle:Day:post}
    requirements:
        _method:  POST